New commits

diff --git a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
--- a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
+++ b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
@@ -1,10 +1,19 @@
 #!/usr/bin/env bash
 
-# Modify the nginx.conf file to run Nginx as the nginx user
-sed -i 's/user\s*root;/user nginx;/g' /etc/nginx/nginx.conf
+# Check if the nginx user exists
+if ! id nginx &>/dev/null; then
+    echo "Error: nginx user does not exist."
+    exit 1
+fi
 
-# Modify the default site configuration to listen on port 8080
+# Update nginx.conf to use the nginx user
+sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
+
+# Update default site configuration to listen on port 8080
 sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
 
-# Restart Nginx to apply the changes
+# Set more restrictive permissions on nginx.conf
+chmod 644 /etc/nginx/nginx.conf
+
+# Restart Nginx service to apply changes
 service nginx restart
